# Generated by Django 4.2.7 on 2023-12-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfood', '0002_foodtruck_facility_type_foodtruck_locationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='blocklot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='cnn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='location_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='lot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
