# Generated by Django 4.2.7 on 2023-12-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfood', '0003_foodtruck_block_foodtruck_blocklot_foodtruck_cnn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='approved',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='dayshours',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='fire_prevention_districts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='location_point',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='neighborhoods_old',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='noisent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='permit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='police_districts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='prior_permit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='received',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='schedule',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='supervisor_districts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='zip_codes',
            field=models.IntegerField(null=True),
        ),
    ]
