# Generated by Django 4.2.7 on 2023-12-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfood', '0004_foodtruck_approved_foodtruck_dayshours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='noisent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
