# Generated by Django 4.2.7 on 2023-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfood', '0006_alter_foodtruck_dayshours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='facility_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
