from django.db import models


class FoodTruck(models.Model):
    applicant = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    locationid = models.CharField(max_length=100, null=True)
    facility_type = models.CharField(max_length=100, blank=True, null=True)
    cnn = models.CharField(max_length=100, null=True)
    location_description = models.CharField(max_length=255, blank=True, null=True)
    blocklot = models.CharField(max_length=100, blank=True, null=True)
    block = models.CharField(max_length=100, blank=True, null=True)
    lot = models.CharField(max_length=100, blank=True, null=True)
    fooditems = models.TextField(blank=True, null=True)
    permit = models.CharField(max_length=100, null=True)
    status = models.CharField(max_length=100, blank=True)
    schedule = models.URLField(null=True)
    dayshours = models.CharField(max_length=255, blank=True, null=True)
    noisent = models.FloatField(null=True, blank=True)
    approved = models.DateField(blank=True, null=True)
    received = models.DateTimeField(null=True)
    prior_permit = models.BooleanField(default=False)
    expiration_date = models.DateField(blank=True, null=True)
    location_point = models.CharField(max_length=255, null=True)
    x = models.FloatField(null=True, blank=True)
    y = models.FloatField(null=True, blank=True)
    fire_prevention_districts = models.IntegerField(null=True, blank=True)
    police_districts = models.IntegerField(null=True, blank=True)
    supervisor_districts = models.IntegerField(null=True, blank=True)
    zip_codes = models.IntegerField(null=True, blank=True)
    neighborhoods_old = models.IntegerField(null=True, blank=True)
